[mypy]
exclude = ^(scripts/|Poster/|alembic/)
ignore_missing_imports = True

[mypy-clarifai_grpc.*]
ignore_missing_imports = True

[mypy-sentence_transformers.*]
ignore_missing_imports = True

[mypy-requests.*]
ignore_missing_imports = True
